// Regenerates the component barrel files:
//
//   packages/hero_ui/lib/src/components/components.dart
//   packages/hero_ui_pro/lib/src/components/components.dart (when present)
//
// Every folder under lib/src/components with a library named after the folder
// (`button/button.dart`) is exported. Run from the repository root:
//
//   dart run tool/generate_exports.dart
import 'dart:io';

void main() {
  for (final String package in <String>[
    'packages/hero_ui',
    'packages/hero_ui_pro',
  ]) {
    final Directory dir = Directory('$package/lib/src/components');
    if (!dir.existsSync()) continue;
    final List<String> exports =
        dir
            .listSync()
            .whereType<Directory>()
            .map(
              (Directory d) =>
                  d.uri.pathSegments[d.uri.pathSegments.length - 2],
            )
            .where(
              (String name) =>
                  File('${dir.path}/$name/$name.dart').existsSync(),
            )
            .map((String name) => "export '$name/$name.dart';")
            .toList()
          ..sort();
    final String path = '${dir.path}/components.dart';
    final StringBuffer out = StringBuffer()
      ..writeln('// Generated by tool/generate_exports.dart. Do not edit.')
      ..writeln();
    if (exports.isEmpty) {
      out.writeln('// Component exports are added as each component lands.');
    } else {
      exports.forEach(out.writeln);
    }
    File(path).writeAsStringSync(out.toString());
    stdout.writeln('$path: ${exports.length} components');
  }
}
