// Regenerates apps/gallery/lib/src/demos/registry.dart from the
// `ComponentDemo` declarations found in apps/gallery/lib/src/demos/*.dart.
//
// Run from the repository root: dart run tool/generate_gallery_registry.dart
import 'dart:io';

void main() {
  final Directory dir = Directory('apps/gallery/lib/src/demos');
  final RegExp decl = RegExp(
    r'^(?:final|const) ComponentDemo (\w+)\s*=',
    multiLine: true,
  );
  final List<(String file, String name)> demos = <(String, String)>[];
  final List<File> files =
      dir
          .listSync()
          .whereType<File>()
          .where(
            (File f) =>
                f.path.endsWith('_demo.dart') &&
                !f.path.endsWith('registry.dart'),
          )
          .toList()
        ..sort((File a, File b) => a.path.compareTo(b.path));
  for (final File file in files) {
    for (final RegExpMatch m in decl.allMatches(file.readAsStringSync())) {
      demos.add((file.uri.pathSegments.last, m.group(1)!));
    }
  }
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// Generated by tool/generate_gallery_registry.dart. Do not edit.',
    )
    ..writeln()
    ..writeln("import '../demo.dart';");
  for (final String file in demos.map(((String, String) d) => d.$1).toSet()) {
    out.writeln("import '$file';");
  }
  out
    ..writeln()
    ..writeln('/// Every component demo, keyed by catalog slug.')
    ..writeln('final Map<String, ComponentDemo> demoRegistry =')
    ..writeln('    <String, ComponentDemo>{');
  for (final (String _, String name) in demos) {
    out.writeln('      $name.slug: $name,');
  }
  out.writeln('    };');
  final String path = '${dir.path}/registry.dart';
  File(path).writeAsStringSync(out.toString());
  Process.runSync('dart', <String>['format', path]);
  stdout.writeln('Registered ${demos.length} demos.');
}
