// Generated by tool/generate_gallery_registry.dart. Do not edit.

import '../demo.dart';
import 'button_demo.dart';
import 'button_group_demo.dart';
import 'close_button_demo.dart';
import 'spinner_demo.dart';

/// Every component demo, keyed by catalog slug.
final Map<String, ComponentDemo> demoRegistry = <String, ComponentDemo>{
  buttonDemo.slug: buttonDemo,
  buttonGroupDemo.slug: buttonGroupDemo,
  closeButtonDemo.slug: closeButtonDemo,
  spinnerDemo.slug: spinnerDemo,
};
