// Generated by tool/generate_gallery_registry.dart. Do not edit.

import '../demo.dart';

/// Every component demo, keyed by catalog slug.
final Map<String, ComponentDemo> demoRegistry = <String, ComponentDemo>{};
