// Generated by tool/generate_gallery_registry.dart. Do not edit.

import '../demo.dart';
import 'avatar_demo.dart';
import 'avatar_group_demo.dart';
import 'badge_demo.dart';
import 'button_demo.dart';
import 'button_group_demo.dart';
import 'chip_demo.dart';
import 'close_button_demo.dart';
import 'input_demo.dart';
import 'kbd_demo.dart';
import 'link_demo.dart';
import 'separator_demo.dart';
import 'spinner_demo.dart';
import 'typography_demo.dart';

/// Every component demo, keyed by catalog slug.
final Map<String, ComponentDemo> demoRegistry = <String, ComponentDemo>{
  avatarDemo.slug: avatarDemo,
  avatarGroupDemo.slug: avatarGroupDemo,
  badgeDemo.slug: badgeDemo,
  buttonDemo.slug: buttonDemo,
  buttonGroupDemo.slug: buttonGroupDemo,
  chipDemo.slug: chipDemo,
  closeButtonDemo.slug: closeButtonDemo,
  inputDemo.slug: inputDemo,
  kbdDemo.slug: kbdDemo,
  linkDemo.slug: linkDemo,
  separatorDemo.slug: separatorDemo,
  spinnerDemo.slug: spinnerDemo,
  typographyDemo.slug: typographyDemo,
};
